### ISSUE TITLE
getXYspectrum selector seems to be not ideally suited for the unitless quantities

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/common-spectrum#2]
I finally got back to the isotherm view and this indeed seems to be a limitation. 

- In some instances there might be multiple unitless quantities 
- In the isotherm case I might have multiple n-tuple jcamps in one file, with multiple unitless columns. So I would rather want the users to be able to select based on the column label 

adding more logic to https://github.com/cheminfo/common-spectrum/blob/4542a08adffb8deefd83b3d72479ebe6adb3c303/src/util/getXYSpectrum.js#L15 doesn't seem to be the best solution but using `selector.xLabel` and `selector.yLabel` can allow for consistency with the old API. 

So maybe we can seperate the cases 1) units provided 2) labels provided and handle the logic for those two cases in smaller functions.

**Comment by kjappelbaum** [comment]
another issue currently is if all xUnit, yUnit and units are undefined

**Comment by lpatiny** [comment]
Closed by https://github.com/cheminfo/common-spectrum/commit/55a5c11ee24fdaeeb43594c599a69e124036126f
