### ISSUE TITLE
eslint fails on getNormalizationAnnotations.js

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/common-spectrum#5]
Probably disabling it here is better than a breaking change? In case of the breaking change Isotherm, TGA and PXRD view need to be changed.  

```
/home/runner/work/common-spectrum/common-spectrum/src/jsgraph/getNormalizationAnnotations.js
Error:   1:45  error  Default parameters should be last  default-param-last
```

**Comment by targos** [comment]
I would technically be a breaking change, but is there anywhere that the method is called without the first parameter? The only way to call it would be `getNormalizationAnnotations(undefined, boundary)`

**Comment by lpatiny** [comment]
closed by https://github.com/cheminfo/common-spectrum/commit/fe56d4d30fb8520442a72245b55d88b7bd334191
